### ISSUE TITLE
Mavenize

### ISSUE THREAD

**Issue by vincentjames501** [frapontillo/ImageViewEx#12]
Mavenizing this project would be incredibly helpful for those of us using maven/gradle for our builds.

**Comment by rock3r** [comment]
We currently are working on a new library that has the same capabilities
ImageViewEx has, and more, and is based upon Volley and NetworkImageView.
What this means is that we're not going to put a lot of effort into
ImageViewEx anymore. Also, at the moment we're not using Maven, so that is
another little problem :)

Of you want to issue a pull request for it, though, we will surely merge
it.

Thanks

**Comment by vincentjames501** [comment]
What's the new library called?  Is it on github yet?

**Comment by rock3r** [comment]
It's still a private repo, we'll have to fix a couple issues before
releasing I'm afraid

**Comment by smarek** [comment]
@rock3r Hi, any update on this? Is the new library ready? Thanks

**Comment by rock3r** [comment]
Hi Marek, the new library is still in the works, we're refactoring a huge
part of the code because we're trying to solve some nasty concurrency
issues when used in ListViews inside convertViews, and it's proving a huge
pain (plus, I've got very little time to work on it at this moment).

Sorry for the delay!

**Comment by rockerhieu** [comment]
Can't wait :+1:. Keep us posted @rock3r

**Comment by radut** [comment]
```
 <repository>
    <id>omentrack-public</id>
    <url>http://nexus.omentrack.com/nexus/content/repositories/public/</url>
 </repository>

<dependency>
     <groupId>net.frakbot</groupId>
     <artifactId>ImageViewEx</artifactId>
     <version>2.1.0-alpha1</version>
</dependency>
```

**Comment by rock3r** [comment]
We now finally have completed the whole Sonatype subscription process and have a library on their repo (SNAPSHOT). Not sure about getting IVE on there or on Maven Central though.

IVE development has been halted because the project it was used in has been put on hiatus, I'm sorry.
